name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://viktorhreptovich.github.io/on-track/playwright-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

  webdriverio-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: allure-report
      url: https://viktorhreptovich.github.io/on-track/allure-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run webserver
        run: npm run dev &
      - name: WebdriverIO tests
        run: npm run wdio
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history
#          keep_files: true
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure
          path: allure-history/
          retention-days: 1
      - name: Upload report allure
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 1


  deploy-reports:
    environment:
      name: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [ playwright-test, webdriverio-test ]
    if: always()
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Display structure of downloaded files
        run: ls -R reports
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: github-pages
          path: reports
      #      - name: Merge Artifacts
      #        uses: actions/upload-artifact/merge@v4
      #        with:
      #          name: github-pages
      #          pattern: github-pages-*
      ##          separate-directories: true
      #          delete-merged: true
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        if: always()


