name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ github.server_url }}/${{ github.repository }}/playwright-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
#      - name: Upload
#        id: upload
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 10
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: github-pages-playwright
          path: reports

  webdriverio-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: link
      url: ${{ github.server_url }}/${{ github.repository }}/allure-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run webserver
        run: npm run dev &
      - name: WebdriverIO tests
        run: npm run wdio
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: reports/allure-results
          allure_history: reports/allure-history
          keep_reports: 20
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: github-pages-allure-report
          path: reports

  deploy-reports:
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [ playwright-test, webdriverio-test ]
    if: always()
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: github-pages
          pattern: github-pages-*
#          separate-directories: true
          delete-merged: true
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        if: always()


